appveyor say error
```
"gcc -o conftest -IC:/Ruby193/include/ruby-1.9.1/i386-mingw32
-IC:/Ruby193/include/ruby-1.9.1/ruby/backward
-IC:/Ruby193/include/ruby-1.9.1 -I. -DFD_SETSIZE=2048  -DFD_SETSIZE=2048
-O3 -fno-omit-frame-pointer -g -Wall -Wextra -Wno-unused-parameter
-Wno-parentheses -Wno-long-long -Wno-missing-field-initializers
-Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement
-Wimplicit-function-declaration conftest.c  -L. -LC:/Ruby193/lib -L.
-march=i486   -lmsvcrt-ruby191  -lshell32 -lws2_32 -limagehlp -lshlwapi
"
In file included from C:/Ruby193/include/ruby-1.9.1/ruby/ruby.h:1382:0,
                 from C:/Ruby193/include/ruby-1.9.1/ruby.h:32,
                 from conftest.c:1:
C:/Ruby193/include/ruby-1.9.1/ruby/missing.h:44:8: error: redefinition
of 'struct timespec'
 struct timespec {
        ^
In file included from c:\mingw\include\unistd.h:95:0,
                 from C:/Ruby193/include/ruby-1.9.1/ruby/win32.h:105,
                 from C:/Ruby193/include/ruby-1.9.1/ruby/defines.h:223,
                 from C:/Ruby193/include/ruby-1.9.1/ruby/ruby.h:67,
                 from C:/Ruby193/include/ruby-1.9.1/ruby.h:32,
                 from conftest.c:1:
c:\mingw\include\parts\time.h:65:8: note: originally defined here
 struct timespec
        ^
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <winsock2.h>
4: #include <windows.h>
5: int main(int argc, char **argv)
6: {
7:   return 0;
8: }
/* end */

rakefile:26:in `load'
```